# Generated by Django 5.1.6 on 2025-04-19 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_recebidas', to='beneficiarios.beneficiario')),
                ('remetente', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'doador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-id'],
            },
        ),
    ]
