# Generated by Django 5.1.2 on 2025-04-20 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio'),
        ),
    ]
