# Generated by Django 5.1.2 on 2025-04-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_alter_mensagem_options_mensagem_data_envio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-data_envio'], 'permissions': [('pode_aprovar', 'Pode aprovar mensagens'), ('pode_rejeitar', 'Pode rejeitar mensagens')], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
