# Generated by Django 5.1.6 on 2025-04-22 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('mensagens', '0003_alter_mensagem_options_mensagem_data_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='aprovador',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='assunto',
            field=models.CharField(max_length=200, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_recebidas', to='beneficiarios.beneficiario', verbose_name='Destinatário'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida?'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'doador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando', max_length=20, verbose_name='Status'),
        ),
    ]
