# Generated by Django 5.2 on 2025-05-12 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Visitação')),
                ('capacidade_maxima', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Capacidade Máxima')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado')], default='disponivel', max_length=10)),
                ('doadores_presentes', models.ManyToManyField(blank=True, related_name='visitas_agendadas', to='usuarios.doador', verbose_name='Doadores Confirmados')),
            ],
            options={
                'verbose_name': 'Data de Visitação',
                'verbose_name_plural': 'Datas de Visitação',
                'ordering': ['data'],
            },
        ),
    ]
