# Generated by Django 5.1.6 on 2025-05-12 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_is_superuser_and_more'),
        ('visitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavisitacao',
            name='capacidade_maxima',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade Máxima'),
        ),
        migrations.AlterField(
            model_name='datavisitacao',
            name='data',
            field=models.DateField(verbose_name='Data da Visitação'),
        ),
        migrations.AlterField(
            model_name='datavisitacao',
            name='doadores_presentes',
            field=models.ManyToManyField(blank=True, related_name='visitas_agendadas', to='usuarios.doador', verbose_name='Doadores Agendados'),
        ),
        migrations.AlterUniqueTogether(
            name='datavisitacao',
            unique_together={('data',)},
        ),
    ]
