# Generated by Django 5.1.6 on 2025-06-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('meta_arrecadacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_arrecadado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('gestor_responsavel', models.ForeignKey(limit_choices_to={'tipo_usuario': 'gestor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
