# Generated by Django 5.1.6 on 2025-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-id'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='data',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Comprovante digital', null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='destino',
            field=models.CharField(choices=[('CURSOS', 'Cursos Profissionalizantes'), ('MATERIAL', 'Material Didático'), ('BOLSAS', 'Bolsas de Estudo'), ('OUTROS', 'Outros')], help_text='Destino dos recursos', max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de Crédito'), ('TRANSFERENCIA', 'Transferência Bancária')], help_text='Forma de pagamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='observacao',
            field=models.TextField(blank=True, help_text='Informações adicionais', null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', help_text='Status atual', max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor em reais', max_digits=10),
        ),
    ]
