# Generated by Django 5.1.6 on 2025-04-14 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0002_alter_doacao_options_remove_doacao_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='comprovante',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='destino',
            field=models.CharField(choices=[('CURSOS', 'Cursos'), ('ALIMENTOS', 'Alimentação'), ('GERAL', 'Geral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de Crédito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
