# Generated by Django 5.1.6 on 2025-04-14 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0003_alter_doacao_options_remove_doacao_comprovante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-id'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterField(
            model_name='doacao',
            name='destino',
            field=models.CharField(choices=[('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('ALIMENTOS', 'Alimentação')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
