# Generated by Django 5.1.6 on 2025-06-03 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
        ('doacoes', '0004_alter_doacao_options_alter_doacao_destino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-data_doacao'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AddField(
            model_name='doacao',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_campanha', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='destino',
            field=models.CharField(blank=True, choices=[('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('ALIMENTOS', 'Alimentação'), ('GERAL', 'Geral/Outros')], max_length=20, null=True),
        ),
    ]
